### PR TITLE
equipe 6

### PR DESCRIPTION
**Pull request by nordinel**

### CODE REVIEW

**Comment by massimotisi** [comment]
not accepting because it contains several changes to the other teams code

**Comment by nordinel** [comment]
there is a space on the file of the team transformateur 2, in the file transformateur 2 that I cannot remove. Besides this, all the other files are ok.

**Comment by massimotisi** [comment]
In eclipse right click on that file -> replace with -> branch, tag or reference... -> and select me among the "remote tracking" branches

**Comment by nordinel** [comment]
it worked thank you

**Pull request merged**
