### PR TITLE
Séance 09/05/2019

### PR DESCRIPTION
**Pull request by ErineDupont**

### CODE REVIEW

**Comment by massimotisi** [comment]
please remove `CACAO2019/.gitignore`

**Comment by massimotisi** [comment]
@ErineDupont you have to accept my invitation to the CACAO2019 organization. You should be in team 6, why are you sending me a file for team 5?

**Comment by ErineDupont** [comment]
I'm in team 5 ! (Distributeur 1)

[ http://www.imt-atlantique.fr/ ] 	
Erine DUPONT 
Etudiante 1ère Année 
Pôle communication - Bureau des élèves 















Une école de [ https://www.imt.fr/ | l'IMT ]

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Erine DUPONT" <erine.dupont@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Mercredi 15 Mai 2019 15:09:37
Objet: Re: [cacao2019/CACAO2019] Séance 09/05/2019 (#22)

@ErineDupont you have to accept my invitation to the CACAO2019 organization. You should be in team 6, why are you sending me a file for team 5?

**Comment by massimotisi** [comment]
@ErineDupont there is no need to close and reopen the pull request

**Comment by ErineDupont** [comment]
[ http://www.imt-atlantique.fr/ ] 	
Erine DUPONT 
Etudiante 1ère Année 
Pôle communication - Bureau des élèves 



i'm trying to delete the .gitignore file but it doesn't seem to work...











Une école de [ https://www.imt.fr/ | l'IMT ]

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Erine DUPONT" <erine.dupont@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 16 Mai 2019 09:42:14
Objet: Re: [cacao2019/CACAO2019] Séance 09/05/2019 (#22)

@ErineDupont there is no need to close and reopen the pull request

**Comment by massimotisi** [comment]
After deleting it you have to commit and push in your repository

**Comment by ErineDupont** [comment]
[ http://www.imt-atlantique.fr/ ] 	
Erine DUPONT 
Etudiante 1ère Année 
Pôle communication - Bureau des élèves 



That's what i've done, but now in the pull request it's all red when it says i've suppressed the file











Une école de [ https://www.imt.fr/ | l'IMT ]

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Erine DUPONT" <erine.dupont@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 16 Mai 2019 09:50:35
Objet: Re: [cacao2019/CACAO2019] Séance 09/05/2019 (#22)

After deleting it you have to commit and push in your repository

**Comment by massimotisi** [comment]
the gitignore file you have to remove is in the CACAO2019 folder: https://github.com/ErineDupont/CACAO2019/blob/master/CACAO2019/.gitignore

**Comment by massimotisi** [comment]
(you removed the wrong gitignore, the one that is in the root folder of the project)

**Comment by massimotisi** [comment]
here you can find the list of changes you made https://github.com/cacao2019/CACAO2019/pull/22/files

**Comment by ErineDupont** [comment]
I think it's ok now ?

**Comment by massimotisi** [comment]
Ok, now you deleted the right one. But you have to restore the main gitignore that you should not have deleted. You can find its contents here: https://github.com/cacao2019/CACAO2019/blob/master/.gitignore

You also have to join the CACAO2019 organization

**Comment by ErineDupont** [comment]
How do i restore the file, i found the content but i don't know how to put it back in the CACAO file


[ http://www.imt-atlantique.fr/ ] 	
Erine DUPONT 
Etudiante 1ère Année 
Pôle communication - Bureau des élèves 















Une école de [ https://www.imt.fr/ | l'IMT ]

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Erine DUPONT" <erine.dupont@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 16 Mai 2019 10:11:20
Objet: Re: [cacao2019/CACAO2019] Séance 09/05/2019 (#22)

Ok, now you deleted the right one. But you have to restore the main gitignore that you should not have deleted. You can find its contents here: https://github.com/cacao2019/CACAO2019/blob/master/.gitignore

You also have to join the CACAO2019 organization

**Comment by massimotisi** [comment]
Go on this page and save the file https://github.com/cacao2019/CACAO2019/raw/master/.gitignore. Then move it in Eclipse -> git perspective -> CACAO2019 -> Working Tree

**Comment by ErineDupont** [comment]
The link gives me only text, how am I supposed to put it on the working tree ? (I found the working tree, just I don't know how to put the code in a new file)

[ http://www.imt-atlantique.fr/ ] 	
Erine DUPONT 
Etudiante 1ère Année 
Pôle communication - Bureau des élèves 















Une école de [ https://www.imt.fr/ | l'IMT ]

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Erine DUPONT" <erine.dupont@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 16 Mai 2019 10:19:07
Objet: Re: [cacao2019/CACAO2019] Séance 09/05/2019 (#22)

Go on this page and save the file https://github.com/cacao2019/CACAO2019/raw/master/.gitignore. Then move it in Eclipse -> git perspective -> CACAO2019 -> Working Tree

**Comment by massimotisi** [comment]
Just save the page from the browser into a file called .gitignore

**Comment by massimotisi** [comment]
@KelianB-IMTA has the same problem, can you interact with him?

**Comment by ErineDupont** [comment]
[ http://www.imt-atlantique.fr/ ] 	
Erine DUPONT 
Etudiante 1ère Année 
Pôle communication - Bureau des élèves 



Ok, we're interacting. 










Une école de [ https://www.imt.fr/ | l'IMT ]

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Erine DUPONT" <erine.dupont@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 16 Mai 2019 10:38:45
Objet: Re: [cacao2019/CACAO2019] Séance 09/05/2019 (#22)

@KelianB-IMTA has the same problem, can you interact with him?

**Comment by massimotisi** [comment]
There must be just one .gitignore, in the root of the project (Working Tree). Not one in the folder CACAO2019!

**Comment by ErineDupont** [comment]
Is it ok now ?

**Comment by massimotisi** [comment]
Super!

**Comment by massimotisi** [comment]
Now you have to accept the invitation to the CACAO2019 organization

**Comment by ErineDupont** [comment]
Where do i find that invitation ?


[ http://www.imt-atlantique.fr/ ] 	
Erine DUPONT 
Etudiante 1ère Année 
Pôle communication - Bureau des élèves 















Une école de [ https://www.imt.fr/ | l'IMT ]

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Erine DUPONT" <erine.dupont@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 16 Mai 2019 11:17:16
Objet: Re: [cacao2019/CACAO2019] Séance 09/05/2019 (#22)

Now you have to accept the invitation to the CACAO2019 organization

**Comment by massimotisi** [comment]
@ErineDupont  you changed the content of gitignore again!

**Comment by massimotisi** [comment]
The invitation should have arrived as an email at the email address you used for subscribing to github

**Comment by ErineDupont** [comment]
I suppressed the line you told me to...

**Comment by massimotisi** [comment]
@ErineDupont you are mixing messages for different groups! please use the github interface to communicate. Your pull request is here: https://github.com/cacao2019/CACAO2019/pull/22

**Comment by ErineDupont** [comment]
i joined the organization

**Comment by ErineDupont** [comment]
is it ok now with the gitignore file ?

**Comment by massimotisi** [comment]
ok!

**Pull request merged**
