### PR TITLE
Equipe 3 Transformateur 1

### PR DESCRIPTION
**Pull request by kThieb**
Version 1 qui fonctionne selon nos tests

### CODE REVIEW

**Comment by massimotisi** [comment]
To resolve the conflict you have to pull from my repository, resolve the conflict in local, commit and push.

**Comment by massimotisi** [comment]
Any news?

**Comment by kThieb** [comment]
I didn't succeed in resolving the conflicts, the commit and push is non fast forward...

**Comment by massimotisi** [comment]
Pull from your repository, handle the conflicts (if any), then create a new commit with all the java files you touched and push again

**Comment by kThieb** [comment]
I think I solved the issue I had. Please tell me if the pull request can be accepted

**Comment by massimotisi** [comment]
Can't accept because you change `CACAO2019/src/abstraction/eq7Romu/acteurs/CreateurRomu.java` and `CACAO2019/src/abstraction/fourni/Monde.java`

**Comment by kThieb** [comment]
I think I finally was able to do it right

**Comment by massimotisi** [comment]
It looks better, but now the test `abstraction.MondeV1Test` crashes

**Comment by kThieb** [comment]
How can I solve this problem ? I dont really understand what failed

**Comment by massimotisi** [comment]
You can find the test in your Eclipse `test/abstraction/MondeV1Test.java`. You can run it on your machine by rightclick on MondeV1Test.java->Run As->Junit Test. If it works on your machine, it will work also on github.

**Comment by kThieb** [comment]
The test worked on my machine, so it should be good for this

**Comment by massimotisi** [comment]
The test is good, but now you re-introduced the changes to `CACAO2019/src/abstraction/eq7Romu/acteurs/CreateurRomu.java` and `CACAO2019/src/abstraction/fourni/Monde.java`(you can see the list of files you are sending in the tab `Files changed` in this page).

**Comment by kThieb** [comment]
I Changed CreateurRomu and Monde again

**Pull request merged**
