### PR TITLE
Pull Request finale

### PR DESCRIPTION
**Pull request by ErineDupont**

### CODE REVIEW

**Comment by massimotisi** [comment]
You have to synchronize your repository with mine

**Comment by ErineDupont** [comment]
I'm trying but it says I can't (dirty work tree)

**Comment by ErineDupont** [comment]
Estelle committed a programm but she had modifications on several files while she did not touch them

**Comment by massimotisi** [comment]
It means that you made some changes to some file and you did not commit those files

**Comment by ErineDupont** [comment]
And it completely destroyed mine, my old code I had modified disappeared

**Comment by ErineDupont** [comment]
I can't commit because I can't pull

**Comment by ErineDupont** [comment]
It says i have conflicts with some eq2 files

**Comment by massimotisi** [comment]
You should be able to commit anyway (without pushing)

**Comment by ErineDupont** [comment]
Okay i did it

**Comment by massimotisi** [comment]
Now you have to pull from me

**Comment by ErineDupont** [comment]
Done, but it gives me conflicts with several files from other teams

**Comment by massimotisi** [comment]
For each one of those files right click -> replace with -> branch, tag or reference... -> and select me among the "remote tracking" branches

**Comment by massimotisi** [comment]
To be faster, you can replace the whole packages of the other teams by right-clicking on them and following the same procedure

**Comment by ErineDupont** [comment]
I do not have branch, tag or reference, it says replace with ours or theirs

**Comment by massimotisi** [comment]
it's probably "theirs"

**Comment by ErineDupont** [comment]
I tried but it does not seem to do anything

**Comment by ErineDupont** [comment]
Not working at all...

**Comment by ErineDupont** [comment]
I can 'replace with index' or 'replace with head revision', should i test one ?

**Comment by massimotisi** [comment]
An alternative solution is:
- first "hard reset" towards my repository: 
Right click on the project root-> Team -> Reset... -> Select "Hard" -> Select my server among the "Remote Tracking" servers  -> Reset
- then replace the files of your team with the version you have now: https://github.com/ErineDupont/CACAO2019/tree/20777936c4744ffbc2b3ea456394fba37b894ac2/CACAO2019/src/abstraction/eq5Distributeur1

**Comment by ErineDupont** [comment]
How do I replace the files ? Just copy & paste ?

**Comment by massimotisi** [comment]
Copy & paste works. 

Otherwise with right click -> "Replace with" -> branch, tag or reference... -> and select the exact commit identifier from your history. In your case it's: 20777936c4744ffbc2b3ea456394fba37b894ac2

**Comment by massimotisi** [comment]
I've merged another pull request, you will have to pull again from my repository

**Comment by ErineDupont** [comment]
Ok i reset and i have copy/paste the works

**Comment by massimotisi** [comment]
Commit and push

**Comment by ErineDupont** [comment]
I pushed and all errors came back...

**Comment by ErineDupont** [comment]
Maybe I should come show you in your office ?

**Comment by massimotisi** [comment]
I'm not in nantes this week

**Comment by ErineDupont** [comment]
Ok

**Comment by ErineDupont** [comment]
So, what should I do now ? It says conflicts with other team files again

**Comment by massimotisi** [comment]
I see, let's go back to the first method:
1) Pull from me
2) Commit moving all files from "Unstage changes" to "Staged changes", and push
3) For all packages of the other groups: right click on the name of the package -> replace with -> branch, tag or reference... -> and select me among the "remote tracking" branches
4) Commit and push

**Comment by ErineDupont** [comment]
Nordin helped me and it seems it worked

**Comment by massimotisi** [comment]
You are still sending me a lot of changes to the other groups, as you can see here: https://github.com/cacao2019/CACAO2019/pull/75/files

To revert them right click on the name of the package -> replace with -> branch, tag or reference... -> and select me among the "remote tracking" branches

**Comment by ErineDupont** [comment]
Those files do not appear anymore as errors in my workspace

**Comment by ErineDupont** [comment]
I think there is only one problem left with the built program

**Comment by ErineDupont** [comment]
CACAO2019/build.xml

**Comment by massimotisi** [comment]
Please do the same also for the `test` folder.

**Comment by massimotisi** [comment]
I've sent you a pull request to give you back the file `build.xml` that you accidentally deleted

**Comment by massimotisi** [comment]
Please accept it here: https://github.com/ErineDupont/CACAO2019/pull/1

**Comment by massimotisi** [comment]
Sorry, wrong folder, please accept also https://github.com/ErineDupont/CACAO2019/pull/2

**Pull request merged**
