### PR TITLE
Modification du 27/05/2019 Distributeur 2

### PR DESCRIPTION
**Pull request by nordinel**

### CODE REVIEW

**Comment by massimotisi** [comment]
Compilation error

**Comment by nordinel** [comment]
I think that It's ok now.
Thank you

**Comment by massimotisi** [comment]
there are still small differences in several files of eq7Romu and fourni. Please just replace them with the original version that you can download here:
https://github.com/cacao2019/CACAO2019/tree/master/CACAO2019

For instance:
https://raw.githubusercontent.com/cacao2019/CACAO2019/master/CACAO2019/src/abstraction/eq7Romu/acteurs/CreateurRomu.java

**Comment by massimotisi** [comment]
Now it's good

**Comment by nordinel** [comment]
Thank you for your help !

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "cacao2019/CACAO2019" <CACAO2019@noreply.github.com>
Cc: "Nordin EL MADRAJ" <nordin.el-madraj@imt-atlantique.net>, "Author" <author@noreply.github.com>
Envoyé: Mercredi 29 Mai 2019 13:35:37
Objet: Re: [cacao2019/CACAO2019] Modification du 27/05/2019 Distributeur 2 (#38)

Now it's good

**Pull request merged**
